### ISSUE TITLE
Problem occurred when I ran DynamicTSPApplicationSparkKafka.java

### ISSUE THREAD

**Issue by NEUXuanyuZheng** [jMetal/jMetalSP#11]
Hi, when I ran DynamicTSPApplicationSparkKafka.java with nyData.txt, only a single point at origin showed as Pareto front in every iteration, and I am curious about why this situation occurred.

**Comment by NEUXuanyuZheng** [comment]
I checked the output directory and found data in FUN*.tsv are all zero. Could u please help me with this!

**Comment by cbarba** [comment]
Hi!,
 we are trying to reproduce your example to fix the issue, what is the algorithm configuration used? Have you used the default configuration? Which Spark and Kafka version are you using?

Thanks!

**Comment by NEUXuanyuZheng** [comment]
Thanks for your reply！！
I just configured the spark home, maybe I configured the algorithm in a wrong way! Besides, I am using Spark 2.4.7 and Kafka 2.11.

**Comment by cbarba** [comment]
Hi,
you are right, the results are always cero, we are going to fix that problem. 

Meanwhile,  you can use the other TSP example in this way:

problem = new MultiobjectiveTSPBuilderFromTSPLIBFiles("data/kroA100.tsp", "data/kroB100.tsp") .build();

Thank you so much for your  feedback.
