### ISSUE TITLE
DataConsumer no genera ficheros de frente de pareto

### ISSUE THREAD

**Issue by alu0100881677** [jMetal/jMetalSP#7]
Buenas, necesito almacenar los frente de pareto de mi problema. A modo de guía he usado la clase DynamicTSPApplication para implementar la misma funcionalidad para mi problema pero en lugar de generar los ficheros solo genera el directorio donde se deberían de almacenar.
<img width="1280" alt="captura de pantalla 2018-05-30 a las 16 05 25" src="https://user-images.githubusercontent.com/22497034/40729236-db1ba614-6423-11e8-87fd-de44dbb61cb2.png">
Me gustaría saber que está sucediendo para poder arreglarlo dado que a la hora de ejecutar el programa no lanza ningún fallo.
Gracias de antemano.

**Comment by ajnebro** [comment]
Hola.
  Acabamos de sacar una nueva versión de jMetalSP. ¿Podrías probarla y ver si con ella se resuelve tu problema?. 

  No dudes en contactar si te surge algún problema.


Un saludo.

**Comment by alu0100881677** [comment]
Buenas.
He probado con la nueva versión pero sigo teniendo el mismo problema a pesar de haber tenido que realizar algunos cambios en el código:
Antes: 
DataConsumer<AlgorithmObservedData<IntegerSolution>> localDirectoryOutputConsumer =
	            new LocalDirectoryOutputConsumer<IntegerSolution>("DirectorioSalida", algorithm);

application.setStreamingRuntime(new DefaultRuntime())
		        .setProblem(problem)
		        .setAlgorithm(algorithm)
		        .addStreamingDataSource(streamingPRBDSource)
		        //.addAlgorithmDataConsumer(localDirectoryOutputConsumer)
		        .addAlgorithmDataConsumer(chartConsumer)
		        .run();
Ahora:
DataConsumer<AlgorithmObservedData<IntegerSolution>> localDirectoryOutputConsumer =
	            new LocalDirectoryOutputConsumer<IntegerSolution>("DirectorioSalida");

application.setStreamingRuntime(new DefaultRuntime())
		        .setProblem(problem)
		        .setAlgorithm(algorithm)
		        .addStreamingDataSource(streamingPRBDSource, problem)
		        //.addAlgorithmDataConsumer(localDirectoryOutputConsumer)
		        .addAlgorithmDataConsumer(chartConsumer)
		        .run();
Le agradezco su ayuda, gracias de antemano.
Un saludo.
