### ISSUE TITLE
¿How to generate pareto Front using dynamicNSGA-II?

### ISSUE THREAD

**Issue by alu0100881677** [jMetal/jMetalSP#8]
hi, i am using the dynamic version of nsga-ii and i dont know how to generate the Pareto fronts. The structure i am using is similar to the example shown in [DynamicTSP](https://github.com/jMetal/jMetalSP/blob/master/jmetalsp-examples/src/main/java/org/uma/jmetalsp/examples/dynamictsp/DynamicTSPApplication.java). Could somebody help me?

**Comment by alu0100881677** [comment]
DynamicNSGA-II is generating files with the supposed pareto fronts but when i represent the content in a graphic i get incoherent things like this
<img width="814" alt="captura de pantalla 2018-06-27 a las 10 39 03" src="https://user-images.githubusercontent.com/22497034/41992288-ed2f86e0-7a3f-11e8-832b-95fc7e57797f.png">

**Comment by ajnebro** [comment]
Hi. I would need more information to try to help you. Is you problem time-dependant or does it change as the TSP (when files with problem information are received and processed)?

**Comment by alu0100881677** [comment]
The problem is time-dependant. Yesterday i saw in a paper a solution that recomend to use https://github.com/jMetal/jMetal/tree/master/jmetal-exec/src/main/java/org/uma/jmetal/utility to get the non-dominated solutions from the approximated front. Is that the correct option in my case?

**Comment by ajnebro** [comment]
That utility if for obtaining a reference Pareto front from a set of files stored in a directory. 

What do you intend to plot exactly?. With jMetalSP you can have the choice of storing in a directory all the fronts generated by NSGA-II, but in that case the aforementioned utiliy is not what you need.

**Comment by alu0100881677** [comment]
I am already storing the fronts in a directory. The problem is that this files contains dominated and non-dominated solutions. In order to take the non-dominated solutions from each front, i am using the utility with each file.

**Comment by ajnebro** [comment]
Do you keep the non-dominated solutions for any reason?. You could easily store files containing only non-dominated solution.

**Comment by alu0100881677** [comment]
I want to represent in a graphic the non-dominated solutions. How can i store files containing only non-dominated solutions?

**Comment by ajnebro** [comment]
There are several aproaches. One is to replace the `update()` method of class  `LocalDirectoryOutputConsumer` by this code:

``` java
  @Override
  public void update(Observable<AlgorithmObservedData<S>> observable, AlgorithmObservedData<S> data) {
    List<S> solutionList = (List<S>)data.getData().get("solutionList") ;
    Archive<S> nonDominatedArchive = new NonDominatedSolutionListArchive<>();
    for (S solution : solutionList) {
      nonDominatedArchive.add(solution) ;
    }
    new SolutionListOutput(nonDominatedArchive.getSolutionList())
            .setSeparator("\t")
            .setFunFileOutputContext(new DefaultFileOutputContext(outputDirectoryName + "/FUN" + fileCounter + ".tsv"))
            .setVarFileOutputContext(new DefaultFileOutputContext(outputDirectoryName + "/VAR" + fileCounter + ".tsv"))
            .print();
    fileCounter++;
  }
```

**Comment by alu0100881677** [comment]
Thank you really much.
